### ISSUE TITLE
Map Guide text

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/ebola#5]
To do:

- [x] Draft language for Map Guide pop up for Ebola visualizations
- [x] Add text to Map Guide pop up for Ebola visualizations (text in comment below)

**Comment by aimeehan1** [comment]
@ksewalk 
Welcome to the Global.health Ebola map!

These geospatial data visualizations allow you to explore data for the 2022 Ebola outbreak in Uganda. Further expansion is possible and our team will continue to track cases through the first 100 days.  

Country View: Explore data at the country level. 
Regional View: Explore data at the sub-national level.

**Comment by ksewalk** [comment]
@aimeehan1 looks good!

**Comment by ksewalk** [comment]
@maciej-zarzeczny re-assigned to you for implementation of the text above!

**Comment by maciej-zarzeczny** [comment]
@ksewalk @aimeehan1 I've added the text, it's now deployed on DEV: https://dev-map.ebola.global.health
