### ISSUE TITLE
Caching on Ebola Map upon first load 

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/ebola#9]
Upon loading global.health and navigating to https://map.ebola.global.health/regional, the initial load shows an outdated case count total. Only upon reloading the link will the correct case count display. Seems to be a caching issue. 

Example of experience here:
https://drive.google.com/file/d/1-KVxJ3cEufjMFnPq-r3W6vTS7ER6nhpc/view?usp=sharing
First time users would be shown incorrect data. So this needs to be fixed.

**Comment by jim-sheldon** [comment]
Fixed by creating Cloudfront invalidation
